os:
  - linux
  - linux-ppc64le
sudo: false
language: node_js
node_js:
  - "4.0"
  - "5"
  - "6"
  - "7"
  - "8"
  - "9"
matrix:
  exclude:
  - os: linux-ppc64le
    node_js: "4.0"

script: 
  - if [[ "$TRAVIS_OS_NAME" == "linux-ppc64le" ]]; then npm install; fi;
